# Generated by Django 2.0.4 on 2018-04-27 08:31

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericmodel',
            name='_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='genericmodel',
            name='scheme',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'age': {'nullable': True, 'type': 'integer'}, 'phone': {'nullable': True, 'type': 'string'}, 'rank': {'nullable': True, 'type': 'number'}}),
        ),
    ]
